import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';

export async function POST(request: Request) {
    try {
        const body = await request.json();
        const { name, phone, email, eventId, type } = body;

        // 1. Create or Find Customer (Simple logic: assuming email/phone unique enough for demo)
        // In a real app we might upsert based on email
        let customer = await prisma.customer.findUnique({
            where: { email },
        });

        if (!customer) {
            customer = await prisma.customer.create({
                data: { name, phone, email },
            });
        }

        // 2. Determine Event
        // If no eventId provided (Field Walk-in), we might need a default "Walk-in" event
        // For now, if eventId is missing, we create a dummy "Field" event or check if one exists
        let targetEventId = eventId;
        if (!targetEventId) {
            // "Daily Walk-in" Logic:
            // Automatically create a separate event container for TODAY (San Antonio Time) if it doesn't exist.
            // Using en-CA (Canada) results in YYYY-MM-DD format, forcing America/Chicago timezone.
            const dateStr = new Date().toLocaleDateString('en-CA', { timeZone: 'America/Chicago' });
            const slug = `walk-in-${dateStr}`;

            const defaultEvent = await prisma.event.upsert({
                where: { slug: slug },
                update: {},
                create: {
                    name: `Walk-in (${dateStr})`,
                    slug: slug,
                    date: new Date(dateStr), // Fix: Use dateStr, 'today' was undefined
                    type: 'FIELD'
                }
            });
            targetEventId = defaultEvent.id;
        }

        // 3. Create Registration
        // Generate the unique QR string. Can be the Registration ID itself or a composite.
        // We'll create the registration first to get the ID, then update if needed, 
        // OR just use a UUID generated by Prisma.
        // Let's pre-generate a unique code or let Prisma do it.
        // We'll use the JSON structure the user saw before: { id, name, phone, type }
        // BUT we need the ID to exist first.

        // Transaction to ensure atomicity if we were doing complex ID generation
        const registration = await prisma.registration.create({
            data: {
                customerId: customer.id,
                eventId: targetEventId,
                qrCodeData: 'TEMP_HOLDER', // Will update immediately
            }
        });

        // Construct the actual QR Data
        const actualQrData = JSON.stringify({
            id: registration.id,
            name: customer.name,
            type: type || 'FIELD'
        });

        // Update with final QR Data
        const finalReg = await prisma.registration.update({
            where: { id: registration.id },
            data: { qrCodeData: actualQrData }
        });

        return NextResponse.json({
            success: true,
            id: finalReg.id,
            qrData: actualQrData
        });

    } catch (error) {
        console.error('Registration Error:', error);
        return NextResponse.json({ success: false, error: 'Registration failed' }, { status: 500 });
    }
}
